projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: src/generated/prisma.graphql
    includes: [
      "src/schema.graphql",  
      "williamimoh/datamodel.graphql",
    ]
    extensions:
      prisma: williamimoh/prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/generated/prisma.ts